### ISSUE TITLE
Code Generation

### ISSUE THREAD

**Issue by Benj1x** [SoftwareMoggers-AAU/P4#12]
- [x] Addition
- [x] Subtraction
- [x] Multiplication
- [ ] Division
- [ ] If-statement (Just have to add code after the branches)
  - [x] Comparison's
- [x] While-loops (missing action to do, if true)
- [ ] For-loops
- [ ]  Variable declarations
- [x] Function jumps
- [ ] Modulo
- [ ] Ternary

**Comment by Kragemand** [comment]
Code generation to Arduino C/C++ instead of to asm
